import { test, expect } from "@playwright/test"
import { createRoom, openDoorstep, joinAs } from "./helpers.js"

test("Morinji's purple theme stays personal through approval, reload and leaving", async ({ browser }) => {
  test.setTimeout(60_000)
  const hostContext = await browser.newContext()
  const playerContext = await browser.newContext({ viewport: { width: 390, height: 844 } })
  try {
    const host = await hostContext.newPage()
    const player = await playerContext.newPage()
    const code = await createRoom(host, { requireApproval: true })
    await openDoorstep(player, code)
    await player.fill("#joinSetupName", "Morinji Player")
    await player.locator('[data-character="morinji"]').click()
    await expect(player.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    await expect(player.locator(".avatar-preview img")).toHaveJSProperty("naturalWidth", 1254)
    await expect(player.locator("#joinSetupSubmit")).toHaveCSS("background-color", "rgb(196, 154, 255)")
    await expect(player.getByRole("tab", { name: "Accessories" })).toBeDisabled()
    await player.screenshot({ path: ".playwright-mcp/morinji-picker-mobile.png", animations: "disabled" })
    await player.locator('[data-character="mahmud"]').click()
    await expect(player.locator("html")).not.toHaveAttribute("data-character-theme")
    await player.locator('[data-character="morinji"]').click()
    await player.click("#joinSetupSubmit")
    await expect(player.locator("#pendingView.active-view")).toBeVisible()
    await expect(player.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    const request = host.locator(".request-row", { hasText: "Morinji Player" })
    await expect(request.locator(".avatar")).toHaveAttribute("data-avatar", "morinji")
    await expect(host.locator("html")).not.toHaveAttribute("data-character-theme")
    await request.locator(".btn-primary").click()
    await expect(player.locator("#playerRoomView.active-view")).toBeVisible()
    await player.reload()
    await expect(player.locator("#playerWelcome .avatar")).toHaveAttribute("data-avatar", "morinji")
    await expect(player.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    await player.screenshot({ path: ".playwright-mcp/morinji-room-mobile.png", animations: "disabled" })
    await player.click("#playerLeaveBtn")
    await player.locator(".confirm-ok").click()
    await expect(player.locator("#homeView.active-view")).toBeVisible()
    await expect(player.locator("html")).not.toHaveAttribute("data-character-theme")
  } finally {
    await hostContext.close()
    await playerContext.close()
  }
})

test("Morinji host keeps purple after reload without changing a guest's theme; cancel clears preview", async ({ browser }) => {
  test.setTimeout(60_000)
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  const previewContext = await browser.newContext()
  try {
    const host = await hostContext.newPage()
    const guest = await guestContext.newPage()
    const code = await createRoom(host, { hostCharacter: "morinji" })
    await expect(host.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    await joinAs(guest, code, "Guest", "ruby")
    await expect(guest.locator("html")).not.toHaveAttribute("data-character-theme")
    await host.reload()
    await expect(host.locator("#adminView.active-view")).toBeVisible()
    await expect(host.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    await expect(host.locator("#assignRolesBtn")).toHaveCSS("background-color", "rgb(196, 154, 255)")
    await host.screenshot({ path: ".playwright-mcp/morinji-host-desktop.png", animations: "disabled" })
    const preview = await previewContext.newPage()
    await preview.goto("/")
    await preview.click(".cta-create")
    await preview.locator(".create-picker-option").first().click()
    await preview.locator(".gi-hero .gi-cta-primary").click()
    await preview.locator('[data-character="morinji"]').click()
    await expect(preview.locator("html")).toHaveAttribute("data-character-theme", "morinji")
    await preview.locator(".host-setup-actions .btn-ghost").click()
    await expect(preview.locator("html")).not.toHaveAttribute("data-character-theme")
  } finally {
    await hostContext.close()
    await guestContext.close()
    await previewContext.close()
  }
})
